[package]
name = "window_registry"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[features]
test-utils = []
test-access = ["test-utils"]

[dependencies]
libc = "0.2"
crossbeam-channel = "0.5"

[build-dependencies]
pkg-config = "0.3"
